package server

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/chi/v5"
	"go.uber.org/zap"

	"github.com/Parsaeffatravesh/tragge/packages/auth"
	"github.com/Parsaeffatravesh/tragge/packages/infra"
	"github.com/Parsaeffatravesh/tragge/packages/notification/inapp"
	"github.com/Parsaeffatravesh/tragge/packages/notification/prefs"
	"github.com/Parsaeffatravesh/tragge/packages/wallet"
)

// handleGetContest returns a single contest by ID.
// GET /api/admin/contests/{id}
func (a *App) handleGetContest(w http.ResponseWriter, r *http.Request) {
	contestID := chi.URLParam(r, "id")
	if contestID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ContestIDRequired})
		return
	}

	ctx := r.Context()
	var c ContestResponse
	err := a.circuits.ExecuteReplica(ctx, func(ctx context.Context) error {
		return a.pool.Replica().QueryRowContext(ctx,
			`SELECT id, name, description, starts_at, ends_at, status, entry_fee_cents, platform_fee_bps, qty_total,
			        duration_type, asset_class, COALESCE(duration_minutes, 0), min_participants, max_participants,
			        registration_deadline, auto_start, commission_rate, is_free, auto_generated,
			        template_id, created_at
			 FROM contests WHERE id = $1`, contestID).Scan(
			&c.ID, &c.Name, &c.Description, &c.StartsAt, &c.EndsAt,
			&c.Status, &c.EntryFeeCents, &c.PlatformFeeBps, &c.QtyTotal,
			&c.DurationType, &c.AssetClass, &c.DurationMinutes, &c.MinParticipants,
			&c.MaxParticipants, &c.RegistrationDeadline, &c.AutoStart, &c.CommissionRate,
			&c.IsFree, &c.AutoGenerated,
			&c.TemplateID, &c.CreatedAt)
	})
	if err == sql.ErrNoRows {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ContestNotFound})
		return
	}
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to query contest", zap.String("contest_id", contestID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	writeJSON(w, http.StatusOK, c)
}

// handleRemoveContestParticipant removes a participant from a contest,
// refunds their entry fee, and sends a notification.
// DELETE /api/admin/contests/{id}/participants/{user_id}
func (a *App) handleRemoveContestParticipant(w http.ResponseWriter, r *http.Request) {
	contestID := chi.URLParam(r, "id")
	userID := chi.URLParam(r, "user_id")
	if contestID == "" || userID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ContestUserIDRequired})
		return
	}

	ctx := r.Context()
	actorID := auth.GetUserID(ctx)

	// Begin transaction so participant removal and refund are atomic
	var tx *sql.Tx
	err := a.circuits.ExecuteDatabase(ctx, func(ctx context.Context) error {
		var beginErr error
		tx, beginErr = a.pool.Primary().BeginTx(ctx, nil)
		return beginErr
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to begin transaction", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}
	defer tx.Rollback()

	// Fetch contest details (entry fee and name) for refund and audit
	var entryFeeCents int64
	var contestName string
	err = tx.QueryRowContext(ctx,
		`SELECT entry_fee_cents, name FROM contests WHERE id = $1`, contestID).
		Scan(&entryFeeCents, &contestName)
	if err != nil {
		if err == sql.ErrNoRows {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ContestNotFound})
			return
		}
		a.log().Error("Failed to query contest details",
			zap.String("contest_id", contestID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	// Delete from contest_participants
	result, err := tx.ExecContext(ctx,
		`DELETE FROM contest_participants WHERE contest_id = $1 AND user_id = $2`, contestID, userID)
	if err != nil {
		a.log().Error("Failed to remove contest participant",
			zap.String("contest_id", contestID),
			zap.String("user_id", userID),
			zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ParticipantNotFound})
		return
	}

	// Refund entry fee if the contest had one
	var refunded bool
	if entryFeeCents > 0 {
		walletSvc := wallet.NewService(a.pool.Primary())
		_, err := walletSvc.RefundContestEntryFeeIdempotent(
			ctx, tx, userID, contestID, contestName, entryFeeCents, wallet.ReasonCodeContestRefundAdmin,
		)
		if err != nil {
			a.log().Error("Failed to refund entry fee for removed participant",
				zap.String("user_id", userID),
				zap.String("contest_id", contestID),
				zap.Int64("amount_cents", entryFeeCents),
				zap.Error(err))
			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.RefundFailed})
			return
		}
		refunded = true
	}

	// Commit the transaction
	if err := tx.Commit(); err != nil {
		a.log().Error("Failed to commit participant removal transaction",
			zap.String("contest_id", contestID),
			zap.String("user_id", userID),
			zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	// Send in-app notification asynchronously (after commit, respects user preferences)
	infra.SafeGo(a.log(), "contest-removal-notification", func() {
		notifCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		enabled, _ := prefs.IsEnabled(notifCtx, a.pool.Replica(), userID, inapp.NotifTypeContestLeft, "in_app")
		if !enabled {
			return
		}
		if err := inapp.CreateContestLeftNotification(notifCtx, a.pool.Primary(), userID, contestID, contestName, refunded); err != nil {
			a.log().Error("Failed to create removal notification",
				zap.String("user_id", userID),
				zap.String("contest_id", contestID),
				zap.Error(err))
		}
	})

	// Write audit log with financial details
	a.logAuditEvent(ctx, actorID, "contest.remove_participant", "contest_participant",
		contestID+"/"+userID, map[string]interface{}{
			"contest_id":      contestID,
			"contest_name":    contestName,
			"user_id":         userID,
			"entry_fee_cents": entryFeeCents,
			"refunded":        refunded,
		})

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"message":  adminMsg.ParticipantRemoved,
		"refunded": refunded,
	})
}

// handleListKYCSubmissions lists KYC submissions with optional status filtering.
// GET /api/admin/kyc
func (a *App) handleListKYCSubmissions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parse query parameters
	status := r.URL.Query().Get("status")

	// Validate status filter against known KYC statuses
	validKYCStatuses := map[string]bool{
		"none": true, "pending": true, "under_review": true,
		"verified": true, "rejected": true, "expired": true,
	}
	if status != "" && !validKYCStatuses[status] {
		writeJSON(w, http.StatusBadRequest, map[string]string{
			"error": adminMsg.KYCInvalidStatus,
		})
		return
	}

	pageStr := r.URL.Query().Get("page")
	perPageStr := r.URL.Query().Get("per_page")
	sortOrder := r.URL.Query().Get("sort")

	page := 1
	perPage := 20

	if pageStr != "" {
		if p, err := strconv.Atoi(pageStr); err == nil && p > 0 {
			page = p
		}
	}
	if perPageStr != "" {
		if pp, err := strconv.Atoi(perPageStr); err == nil && pp > 0 && pp <= 100 {
			perPage = pp
		}
	}

	offset := (page - 1) * perPage

	// Build WHERE clause based on status filter
	whereClause := "WHERE 1=1"
	args := []interface{}{}
	argIdx := 1

	if status != "" {
		whereClause += fmt.Sprintf(" AND uv.status = $%d", argIdx)
		args = append(args, status)
		argIdx++
	}

	// Count total
	var total int
	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM user_verification uv JOIN users u ON u.id = uv.user_id %s`, whereClause)
	err := a.circuits.ExecuteReplica(ctx, func(ctx context.Context) error {
		return a.pool.Replica().QueryRowContext(ctx, countQuery, args...).Scan(&total)
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to count KYC submissions", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	// Determine sort direction
	orderDir := "ASC"
	if sortOrder == "newest" {
		orderDir = "DESC"
	}

	// Query submissions
	query := fmt.Sprintf(`SELECT
			uv.user_id,
			u.email,
			uv.first_name,
			uv.last_name,
			(SELECT document_type::TEXT FROM kyc_documents WHERE user_id = uv.user_id ORDER BY created_at DESC LIMIT 1) as document_type,
			uv.status,
			uv.created_at,
			uv.provider,
			uv.shahkar_verified,
			uv.face_verified,
			uv.card_ocr_verified,
			uv.face_match_score
		 FROM user_verification uv
		 JOIN users u ON u.id = uv.user_id
		 %s
		 ORDER BY uv.created_at %s
		 LIMIT $%d OFFSET $%d`, whereClause, orderDir, argIdx, argIdx+1)
	args = append(args, perPage, offset)

	result, err := a.circuits.ExecuteReplicaWithResult(ctx,
		func(ctx context.Context) (interface{}, error) {
			return a.pool.Replica().QueryContext(ctx, query, args...)
		},
	)
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to query KYC submissions", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}
	rows := result.(*sql.Rows)
	defer rows.Close()

	var submissions []KYCPendingSubmission
	for rows.Next() {
		var s KYCPendingSubmission
		var faceMatchScore sql.NullFloat64
		if err := rows.Scan(&s.UserID, &s.Email, &s.FirstName, &s.LastName, &s.DocumentType, &s.Status, &s.SubmittedAt,
			&s.Provider, &s.ShahkarVerified, &s.FaceVerified, &s.CardOCRVerified, &faceMatchScore); err != nil {
			a.log().Error("Failed to scan KYC submission", zap.Error(err))
			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
			return
		}
		if faceMatchScore.Valid {
			s.FaceMatchScore = &faceMatchScore.Float64
		}
		s.AutoApproved = s.ShahkarVerified && s.FaceVerified && s.CardOCRVerified &&
			faceMatchScore.Valid && faceMatchScore.Float64 > 0.85
		submissions = append(submissions, s)
	}

	if err := rows.Err(); err != nil {
		a.log().Error("Failed to iterate KYC submissions", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	if submissions == nil {
		submissions = []KYCPendingSubmission{}
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"submissions": submissions,
		"total":       total,
		"page":        page,
		"per_page":    perPage,
	})
}

// ShardDetail represents detailed info about a single trading engine shard/instance.
type ShardDetail struct {
	ID               string    `json:"id"`
	Status           string    `json:"status"`
	ContestCount     int       `json:"contest_count"`
	ParticipantCount int       `json:"participant_count"`
	OrdersPerSec     float64   `json:"orders_per_sec"`
	MemoryUsageMB    float64   `json:"memory_usage_mb"`
	CPUUsagePercent  float64   `json:"cpu_usage_percent"`
	ConnectionCount  int       `json:"connection_count"`
	LastSeen         time.Time `json:"last_seen"`
}

// handleGetShard returns details for a specific shard/instance.
// GET /api/admin/health/shards/{shardId}
func (a *App) handleGetShard(w http.ResponseWriter, r *http.Request) {
	shardID := chi.URLParam(r, "shardId")
	if shardID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ShardIDRequired})
		return
	}

	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()

	// Look up the shard in Redis heartbeat data
	key := fmt.Sprintf("shard:heartbeat:%s", shardID)
	redisResult, err := a.circuits.ExecuteRedisWithResult(ctx,
		func(ctx context.Context) (interface{}, error) {
			return a.redis.Client().HGetAll(ctx, key).Result()
		},
	)
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ShardNotFound})
		return
	}
	data := redisResult.(map[string]string)
	if len(data) == 0 {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ShardNotFound})
		return
	}

	detail := ShardDetail{
		ID:     shardID,
		Status: data["status"],
	}

	if v, err := strconv.Atoi(data["contest_count"]); err == nil {
		detail.ContestCount = v
	}
	if v, err := strconv.Atoi(data["participant_count"]); err == nil {
		detail.ParticipantCount = v
	}
	if v, err := strconv.ParseFloat(data["orders_per_sec"], 64); err == nil {
		detail.OrdersPerSec = v
	}
	if v, err := strconv.ParseFloat(data["memory_usage_mb"], 64); err == nil {
		detail.MemoryUsageMB = v
	}
	if v, err := strconv.ParseFloat(data["cpu_usage_percent"], 64); err == nil {
		detail.CPUUsagePercent = v
	}
	if v, err := strconv.Atoi(data["connection_count"]); err == nil {
		detail.ConnectionCount = v
	}
	if t, err := time.Parse(time.RFC3339, data["last_seen"]); err == nil {
		detail.LastSeen = t
	}

	writeJSON(w, http.StatusOK, detail)
}

// handleDrainShard sets a shard to draining status so no new contests are assigned.
// POST /api/admin/health/shards/{shardId}/drain
func (a *App) handleDrainShard(w http.ResponseWriter, r *http.Request) {
	shardID := chi.URLParam(r, "shardId")
	if shardID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ShardIDRequired})
		return
	}

	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()
	actorID := auth.GetUserID(ctx)

	key := fmt.Sprintf("shard:heartbeat:%s", shardID)
	err := a.circuits.ExecuteRedis(ctx, func(ctx context.Context) error {
		return a.redis.Client().HSet(ctx, key, "status", "draining").Err()
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to drain shard", zap.String("shard_id", shardID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.ShardDrainFailed})
		return
	}

	a.logAuditEvent(ctx, actorID, "shard.drain", "shard", shardID, map[string]string{"shard_id": shardID})

	writeJSON(w, http.StatusOK, map[string]string{"message": adminMsg.ShardDraining, "shard_id": shardID})
}

// handleActivateShard sets a shard back to active status.
// POST /api/admin/health/shards/{shardId}/activate
func (a *App) handleActivateShard(w http.ResponseWriter, r *http.Request) {
	shardID := chi.URLParam(r, "shardId")
	if shardID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ShardIDRequired})
		return
	}

	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()
	actorID := auth.GetUserID(ctx)

	key := fmt.Sprintf("shard:heartbeat:%s", shardID)
	err := a.circuits.ExecuteRedis(ctx, func(ctx context.Context) error {
		return a.redis.Client().HSet(ctx, key, "status", "active").Err()
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to activate shard", zap.String("shard_id", shardID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.ShardActivateFailed})
		return
	}

	a.logAuditEvent(ctx, actorID, "shard.activate", "shard", shardID, map[string]string{"shard_id": shardID})

	writeJSON(w, http.StatusOK, map[string]string{"message": adminMsg.ShardActivated, "shard_id": shardID})
}

// ShardStatsEntry represents a point-in-time snapshot of shard metrics.
type ShardStatsEntry struct {
	ShardID          string    `json:"shard_id"`
	Timestamp        time.Time `json:"timestamp"`
	OrdersPerSec     float64   `json:"orders_per_sec"`
	ParticipantCount int       `json:"participant_count"`
	ContestCount     int       `json:"contest_count"`
}

// handleGetShardStats returns aggregated shard statistics.
// GET /api/admin/health/shards/stats
func (a *App) handleGetShardStats(w http.ResponseWriter, r *http.Request) {
	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()

	// Get all shard heartbeats and compile stats
	instances, err := a.getInstanceHeartbeats(ctx)
	if err != nil {
		a.log().Warn("Failed to get instance heartbeats for stats", zap.Error(err))
		writeJSON(w, http.StatusOK, map[string]interface{}{"stats": []ShardStatsEntry{}})
		return
	}

	now := time.Now().UTC()
	var stats []ShardStatsEntry
	for _, inst := range instances {
		stats = append(stats, ShardStatsEntry{
			ShardID:   inst.InstanceID,
			Timestamp: now,
		})
	}

	if stats == nil {
		stats = []ShardStatsEntry{}
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{"stats": stats})
}
