package server

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"go.uber.org/zap"

	"github.com/Parsaeffatravesh/tragge/packages/auth"
)

type participantRemovalRequest struct {
	Reason    string `json:"reason"`
	Refund    *bool  `json:"refund,omitempty"`
	AdminNote string `json:"admin_note,omitempty"`
}

func (r participantRemovalRequest) refundDecision() (bool, bool) {
	switch r.Reason {
	case "USER_IMMEDIATE_EXIT_REQUEST":
		return true, r.Refund == nil || *r.Refund
	case "OTHER":
		return true, strings.TrimSpace(r.AdminNote) != "" && (r.Refund == nil || *r.Refund)
	case "CHEATING":
		return r.Refund != nil && *r.Refund, r.Refund != nil
	default:
		return false, false
	}
}

// handleGetContest returns a single contest by ID.
// GET /api/admin/contests/{id}
func (a *App) handleGetContest(w http.ResponseWriter, r *http.Request) {
	contestID := chi.URLParam(r, "id")
	if contestID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ContestIDRequired})
		return
	}

	ctx := r.Context()
	var c ContestResponse
	err := a.circuits.ExecuteReplica(ctx, func(ctx context.Context) error {
		return a.pool.Replica().QueryRowContext(ctx,
			`SELECT id, name, description, starts_at, ends_at, status, entry_fee_cents, platform_fee_bps, qty_total,
			        duration_type, asset_class, COALESCE(duration_minutes, 0), min_participants, max_participants,
			        registration_deadline, auto_start, commission_rate, is_free, auto_generated,
			        template_id, created_at
			 FROM contests WHERE id = $1`, contestID).Scan(
			&c.ID, &c.Name, &c.Description, &c.StartsAt, &c.EndsAt,
			&c.Status, &c.EntryFeeCents, &c.PlatformFeeBps, &c.QtyTotal,
			&c.DurationType, &c.AssetClass, &c.DurationMinutes, &c.MinParticipants,
			&c.MaxParticipants, &c.RegistrationDeadline, &c.AutoStart, &c.CommissionRate,
			&c.IsFree, &c.AutoGenerated,
			&c.TemplateID, &c.CreatedAt)
	})
	if err == sql.ErrNoRows {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ContestNotFound})
		return
	}
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to query contest", zap.String("contest_id", contestID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	writeJSON(w, http.StatusOK, c)
}

// handleRemoveContestParticipant removes a participant from a contest,
// refunds their entry fee, and sends a notification.
// DELETE /api/admin/contests/{id}/participants/{user_id}
func (a *App) handleRemoveContestParticipant(w http.ResponseWriter, r *http.Request) {
	contestID := chi.URLParam(r, "id")
	userID := chi.URLParam(r, "user_id")
	if contestID == "" || userID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ContestUserIDRequired})
		return
	}

	ctx := r.Context()
	actorID := auth.GetUserID(ctx)
	var req participantRemovalRequest
	if r.Body == nil || json.NewDecoder(r.Body).Decode(&req) != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "reason is required"})
		return
	}
	req.AdminNote = strings.TrimSpace(req.AdminNote)
	_, valid := req.refundDecision()
	if !valid {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "reason/refund decision is invalid"})
		return
	}

	result, err := a.removeParticipantAtomic(ctx, contestID, userID, actorID, req)
	if errors.Is(err, errEconomicsCutoff) {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "ECONOMICS_CUTOFF_ADJUSTMENT_REQUIRED"})
		return
	}
	if errors.Is(err, errParticipantInactive) {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "PARTICIPANT_NOT_ACTIVE"})
		return
	}
	if errors.Is(err, sql.ErrNoRows) {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ParticipantNotFound})
		return
	}
	if err != nil {
		a.log().Error("Atomic participant removal failed", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"message":  adminMsg.ParticipantRemoved,
		"refunded": result.Refunded,
		"event_id": result.EventID,
	})
}

// handleListKYCSubmissions lists KYC submissions with optional status filtering.
// GET /api/admin/kyc
func (a *App) handleListKYCSubmissions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parse query parameters
	status := r.URL.Query().Get("status")

	// Validate status filter against known KYC statuses
	validKYCStatuses := map[string]bool{
		"none": true, "pending": true, "under_review": true,
		"verified": true, "rejected": true, "expired": true,
	}
	if status != "" && !validKYCStatuses[status] {
		writeJSON(w, http.StatusBadRequest, map[string]string{
			"error": adminMsg.KYCInvalidStatus,
		})
		return
	}

	pageStr := r.URL.Query().Get("page")
	perPageStr := r.URL.Query().Get("per_page")
	sortOrder := r.URL.Query().Get("sort")

	page := 1
	perPage := 20

	if pageStr != "" {
		if p, err := strconv.Atoi(pageStr); err == nil && p > 0 {
			page = p
		}
	}
	if perPageStr != "" {
		if pp, err := strconv.Atoi(perPageStr); err == nil && pp > 0 && pp <= 100 {
			perPage = pp
		}
	}

	offset := (page - 1) * perPage

	// Build WHERE clause based on status filter
	whereClause := "WHERE 1=1"
	args := []interface{}{}
	argIdx := 1

	if status != "" {
		whereClause += fmt.Sprintf(" AND uv.status = $%d", argIdx)
		args = append(args, status)
		argIdx++
	}

	// Count total
	var total int
	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM user_verification uv JOIN users u ON u.id = uv.user_id %s`, whereClause)
	err := a.circuits.ExecuteReplica(ctx, func(ctx context.Context) error {
		return a.pool.Replica().QueryRowContext(ctx, countQuery, args...).Scan(&total)
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to count KYC submissions", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	// Determine sort direction
	orderDir := "ASC"
	if sortOrder == "newest" {
		orderDir = "DESC"
	}

	// Query submissions
	query := fmt.Sprintf(`SELECT
			uv.user_id,
			u.email,
			uv.first_name,
			uv.last_name,
			(SELECT document_type::TEXT FROM kyc_documents WHERE user_id = uv.user_id ORDER BY created_at DESC LIMIT 1) as document_type,
			uv.status,
			uv.created_at,
			uv.provider,
			uv.shahkar_verified,
			uv.face_verified,
			uv.card_ocr_verified,
			uv.face_match_score
		 FROM user_verification uv
		 JOIN users u ON u.id = uv.user_id
		 %s
		 ORDER BY uv.created_at %s
		 LIMIT $%d OFFSET $%d`, whereClause, orderDir, argIdx, argIdx+1)
	args = append(args, perPage, offset)

	result, err := a.circuits.ExecuteReplicaWithResult(ctx,
		func(ctx context.Context) (interface{}, error) {
			return a.pool.Replica().QueryContext(ctx, query, args...)
		},
	)
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to query KYC submissions", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}
	rows := result.(*sql.Rows)
	defer rows.Close()

	var submissions []KYCPendingSubmission
	for rows.Next() {
		var s KYCPendingSubmission
		var faceMatchScore sql.NullFloat64
		if err := rows.Scan(&s.UserID, &s.Email, &s.FirstName, &s.LastName, &s.DocumentType, &s.Status, &s.SubmittedAt,
			&s.Provider, &s.ShahkarVerified, &s.FaceVerified, &s.CardOCRVerified, &faceMatchScore); err != nil {
			a.log().Error("Failed to scan KYC submission", zap.Error(err))
			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
			return
		}
		if faceMatchScore.Valid {
			s.FaceMatchScore = &faceMatchScore.Float64
		}
		s.AutoApproved = s.ShahkarVerified && s.FaceVerified && s.CardOCRVerified &&
			faceMatchScore.Valid && faceMatchScore.Float64 > 0.85
		submissions = append(submissions, s)
	}

	if err := rows.Err(); err != nil {
		a.log().Error("Failed to iterate KYC submissions", zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.InternalError})
		return
	}

	if submissions == nil {
		submissions = []KYCPendingSubmission{}
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"submissions": submissions,
		"total":       total,
		"page":        page,
		"per_page":    perPage,
	})
}

// ShardDetail represents detailed info about a single trading engine shard/instance.
type ShardDetail struct {
	ID               string    `json:"id"`
	Status           string    `json:"status"`
	ContestCount     int       `json:"contest_count"`
	ParticipantCount int       `json:"participant_count"`
	OrdersPerSec     float64   `json:"orders_per_sec"`
	MemoryUsageMB    float64   `json:"memory_usage_mb"`
	CPUUsagePercent  float64   `json:"cpu_usage_percent"`
	ConnectionCount  int       `json:"connection_count"`
	LastSeen         time.Time `json:"last_seen"`
}

// handleGetShard returns details for a specific shard/instance.
// GET /api/admin/health/shards/{shardId}
func (a *App) handleGetShard(w http.ResponseWriter, r *http.Request) {
	shardID := chi.URLParam(r, "shardId")
	if shardID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ShardIDRequired})
		return
	}

	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()

	// Look up the shard in Redis heartbeat data
	key := fmt.Sprintf("shard:heartbeat:%s", shardID)
	redisResult, err := a.circuits.ExecuteRedisWithResult(ctx,
		func(ctx context.Context) (interface{}, error) {
			return a.redis.Client().HGetAll(ctx, key).Result()
		},
	)
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ShardNotFound})
		return
	}
	data := redisResult.(map[string]string)
	if len(data) == 0 {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": adminMsg.ShardNotFound})
		return
	}

	detail := ShardDetail{
		ID:     shardID,
		Status: data["status"],
	}

	if v, err := strconv.Atoi(data["contest_count"]); err == nil {
		detail.ContestCount = v
	}
	if v, err := strconv.Atoi(data["participant_count"]); err == nil {
		detail.ParticipantCount = v
	}
	if v, err := strconv.ParseFloat(data["orders_per_sec"], 64); err == nil {
		detail.OrdersPerSec = v
	}
	if v, err := strconv.ParseFloat(data["memory_usage_mb"], 64); err == nil {
		detail.MemoryUsageMB = v
	}
	if v, err := strconv.ParseFloat(data["cpu_usage_percent"], 64); err == nil {
		detail.CPUUsagePercent = v
	}
	if v, err := strconv.Atoi(data["connection_count"]); err == nil {
		detail.ConnectionCount = v
	}
	if t, err := time.Parse(time.RFC3339, data["last_seen"]); err == nil {
		detail.LastSeen = t
	}

	writeJSON(w, http.StatusOK, detail)
}

// handleDrainShard sets a shard to draining status so no new contests are assigned.
// POST /api/admin/health/shards/{shardId}/drain
func (a *App) handleDrainShard(w http.ResponseWriter, r *http.Request) {
	shardID := chi.URLParam(r, "shardId")
	if shardID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ShardIDRequired})
		return
	}

	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()
	actorID := auth.GetUserID(ctx)

	key := fmt.Sprintf("shard:heartbeat:%s", shardID)
	err := a.circuits.ExecuteRedis(ctx, func(ctx context.Context) error {
		return a.redis.Client().HSet(ctx, key, "status", "draining").Err()
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to drain shard", zap.String("shard_id", shardID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.ShardDrainFailed})
		return
	}

	a.logAuditEvent(ctx, actorID, "shard.drain", "shard", shardID, map[string]string{"shard_id": shardID})

	writeJSON(w, http.StatusOK, map[string]string{"message": adminMsg.ShardDraining, "shard_id": shardID})
}

// handleActivateShard sets a shard back to active status.
// POST /api/admin/health/shards/{shardId}/activate
func (a *App) handleActivateShard(w http.ResponseWriter, r *http.Request) {
	shardID := chi.URLParam(r, "shardId")
	if shardID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": adminMsg.ShardIDRequired})
		return
	}

	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()
	actorID := auth.GetUserID(ctx)

	key := fmt.Sprintf("shard:heartbeat:%s", shardID)
	err := a.circuits.ExecuteRedis(ctx, func(ctx context.Context) error {
		return a.redis.Client().HSet(ctx, key, "status", "active").Err()
	})
	if err != nil {
		if a.isCircuitError(w, err) {
			return
		}
		a.log().Error("Failed to activate shard", zap.String("shard_id", shardID), zap.Error(err))
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": adminMsg.ShardActivateFailed})
		return
	}

	a.logAuditEvent(ctx, actorID, "shard.activate", "shard", shardID, map[string]string{"shard_id": shardID})

	writeJSON(w, http.StatusOK, map[string]string{"message": adminMsg.ShardActivated, "shard_id": shardID})
}

// ShardStatsEntry represents a point-in-time snapshot of shard metrics.
type ShardStatsEntry struct {
	ShardID          string    `json:"shard_id"`
	Timestamp        time.Time `json:"timestamp"`
	OrdersPerSec     float64   `json:"orders_per_sec"`
	ParticipantCount int       `json:"participant_count"`
	ContestCount     int       `json:"contest_count"`
}

// handleGetShardStats returns aggregated shard statistics.
// GET /api/admin/health/shards/stats
func (a *App) handleGetShardStats(w http.ResponseWriter, r *http.Request) {
	if a.redis == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": adminMsg.RedisUnavailable})
		return
	}

	ctx := r.Context()

	// Get all shard heartbeats and compile stats
	instances, err := a.getInstanceHeartbeats(ctx)
	if err != nil {
		a.log().Warn("Failed to get instance heartbeats for stats", zap.Error(err))
		writeJSON(w, http.StatusOK, map[string]interface{}{"stats": []ShardStatsEntry{}})
		return
	}

	now := time.Now().UTC()
	var stats []ShardStatsEntry
	for _, inst := range instances {
		stats = append(stats, ShardStatsEntry{
			ShardID:   inst.InstanceID,
			Timestamp: now,
		})
	}

	if stats == nil {
		stats = []ShardStatsEntry{}
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{"stats": stats})
}
