#!/usr/bin/env bash
# RETIRED BY FND-004: this script exits before the historical body below.
# The historical text remains only as legacy traceability until cutover.
# squash-migrations.sh — Generate a baseline migration from the current schema.
#
# Usage:
#   1. Ensure PostgreSQL is running with all migrations applied
#   2. Run: ./scripts/squash-migrations.sh
#   3. Verify 0000_baseline.up.sql looks correct
#   4. Move old migrations to archive: mv packages/db/migrations/00{01..79}* packages/db/migrations/archive/
#   5. For existing databases, force the version: migrate force 79
#
# New migrations start from 0080.
set -euo pipefail
cat >&2 <<'EOF'
REFUSED: the legacy schema-squash workflow is retired by FND-004.

It generated an unreviewed public-schema dump, suggested deleting only part of
the legacy chain, and used migrate force without proving schema state. Use
docs/architecture/database-migration-reset-strategy.md and the guarded
scripts/database-reset.mjs workflow. No database command was executed.
EOF
exit 1

DB_URL="${DATABASE_URL:-postgres://tragge_admin:password@localhost:5432/app?sslmode=disable}"
BASELINE="packages/db/migrations/0000_baseline.up.sql"

echo "Generating baseline from current schema..."
pg_dump --schema-only --no-owner --no-privileges --no-comments \
  "$DB_URL" > "$BASELINE"

echo "-- Generated by squash-migrations.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$BASELINE"
echo ""
echo "Baseline written to $BASELINE ($(wc -l < "$BASELINE") lines)"
echo ""
echo "Next steps:"
echo "  1. Review the baseline file"
echo "  2. Move old migrations: mv packages/db/migrations/00{01..79}* packages/db/migrations/archive/"
echo "  3. For existing databases: migrate -path packages/db/migrations -database \$DATABASE_URL force 79"
echo "  4. New migrations start from 0080"
